import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Header from "./components/Header";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body className={`${montserrat.className} bg-white text-black`} >
     <div className="app-container w-full min-h-screen">
        <Navigation />
        <main className="content">
          <Header/>
          {children}
        </main>
      </div>
     </body>
    </html>
  );
}